Update workflow
Docker no longer allowing removal of build container.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -110,14 +110,15 @@ jobs:
             exit 1
           fi
           
-          echo " "
-          echo "Remove the build container"
-          docker rmi ${IMAGE}:build
-          status=$?
-          if [ $status -ne 0 ]; then
-            echo "Error: stop status $status"
-            exit 1
-          fi
+          #echo " "
+          #echo "Remove the build container"
+          #docker rmi ${IMAGE}:build
+          #status=$?
+          #if [ $status -ne 0 ]; then
+            #echo "Error: stop status $status"
+            #exit 1
+          #fi
+          docker images --format "{{.Repository}}:{{.Tag}}"
           
       - name: Push the image
         env:
